### ISSUE TITLE
Reference Kevin Stone's contribution

### ISSUE THREAD

**Issue by pydanny** [audiolion/django-behaviors#1]
Per asked on reddit, Kevin Stone should get proper accreditation.

https://www.reddit.com/r/django/comments/5u0t6t/djangobehaviors_integrate_core_common_behaviors/ddrif5z/

**Comment by audiolion** [comment]
Agreed 👍  Fixed in d035c84ca0b0743457b61f9b79a6994204b30bcf

**Comment by pydanny** [comment]
Perhaps it should link to http://blog.kevinastone.com/django-model-behaviors.html instead of the reddit comment? 😉

**Comment by audiolion** [comment]
Ugh, had the wrong URL on my clipboard, thanks @pydanny I think I blindly copied the url you pasted above lol. Shoulda written some tests >.>

Now actually fixed 589857eb367cdc8dbe073c4b5cebf9f236b26de9
