### ISSUE TITLE
[Suggestion] Option to allow nonunique slug

### ISSUE THREAD

**Issue by vonmaster** [audiolion/django-behaviors#13]
* Django Behaviors version: 0.5.0
* Django version: 2.2.5
* Python version: 3.7.8
* Operating System: Windows 10 64 bits

### Description

Hi. First of all, thank you for this very useful library.

I was wondering if you could consider adding an option (say `SLUG_UNIQUE = TRUE`) to allow enforcing or not unique slugs depending on the use case.

In my situation, since I rely on the ID and the slug to form URLs, I don't need a unique slug (for example, `/5/the-wire` and `/10/the-wire` is the wanted result and not `/10/the-wire-1`).

Would you accept a pull request in that sense? 
The change is fairly simple and would provide more flexibility to developers.

**Comment by audiolion** [comment]
@vonmaster sure thing I would accept a PR for it.

**Comment by audiolion** [comment]
@vonmaster uploaded 0.5.1 https://pypi.org/project/django-behaviors/0.5.1/

Can you let me know if everything goes smoothly integrating into your project? Thanks!

**Comment by vonmaster** [comment]
@audiolion Thank you very much. I installed the package through pip, and everything worked as expected. I changed the setting `UNIQUE_SLUG_BEHAVIOR` to observe the behavior and no issue to report. Again thank you for your support and promptness. I guess the issue can be closed.

**Comment by audiolion** [comment]
You made it happen, thanks for the contribution!
