### ISSUE TITLE
`awesome-slugify` dependency should be optional.

### ISSUE THREAD

**Issue by richardnias** [audiolion/django-behaviors#5]
* Django Behaviors version: 0.4.0
* Django version: 2.0.5
* Python version: 3.6
* Operating System: Mac OS

### Description

I was previously using `django-behaviours==0.2.0`, but need to upgrade for Django 2 support. I have a dependency in my project, `unicode-slugify`, which clashes with `awesome-slugify` (both are imported via `import slugify`), but have incompatible APIs.

### What I Did

When I try and install version `0.4.0`, this clash breaks my project, as `awesome-slugify` is being imported in places where I mean to use `unicode-slugify`.

I think, as the `awesome-slugify` package is only required for the `Slugged` behaviour, the dependency should be listed in `extras`, rather than `install_requires`.

Happy to open a PR for this if you would like.

**Comment by audiolion** [comment]
Hey, yeah I actually grappled with this myself wondering where it should be placed. I am happy to accept a PR to move this into an extras and provide a fallback (django's slugify) or something
