### ISSUE TITLE
Adding db_index to modified field

### ISSUE THREAD

**Issue by kazqvaizer** [audiolion/django-behaviors#9]
What do you think about adding `db_index=True` to [modified](https://github.com/audiolion/django-behaviors/blob/4d987931f175a2a39fa43973612e7280dc12be82/behaviors/behaviors.py#L154) field in `Timestamped` model?

It`s seems to me that filtering or ordering by modified date are very common things to do with timestamped queryset and it could increase performance.

**Comment by f213** [comment]
Actually we use the `modified` field as the cache key in our projects, and after 1m records performance becomes poor. Adding index could solve this problem for us and for all future users of django-behaviors

**Comment by audiolion** [comment]
Yeah certainly we could add this, I dont know why but I never got notification pings on this. Do you want to make a PR for it? Otherwise I should be able to get to it within a week or two, just ping me if I forget again :P
